package com.pm.javagateway.security;

import com.pm.javagateway.config.AiInferenceGrpcClient;
import org.springframework.web.reactive.socket.WebSocketHandler;
import org.springframework.web.reactive.socket.WebSocketMessage;
import org.springframework.web.reactive.socket.WebSocketSession;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class CompanionWebSocketHandler implements WebSocketHandler {

    private final AiInferenceGrpcClient grpcClient;
    private final SanitizationUtility sanitizer;

    public CompanionWebSocketHandler(AiInferenceGrpcClient grpcClient, SanitizationUtility sanitizer){
        this.grpcClient = grpcClient;
        this.sanitizer = sanitizer;
    }



    @Override
    public Mono<Void> handle(WebSocketSession session) {
        // retrive the validated user identity injected by JwtWebSocketHandshakeFilter
        // cast into string. if it is null the connection shoudn't have reached this point

        String userId = (String) session.getAttributes().get("SECURE_USER_ID");

        // async listner for incomming message on this specific socket
        Flux<WebSocketMessage> outFlux = session.receive()
                .flatMap(inboundMessage ->{
                    // extract the raw string payload from the client's WebSocket frame.
                    String rawText = inboundMessage.getPayloadAsText();

                    // Neutralize protential prompt injection vector before processing
                    String cleanText = sanitizer.stripInjectionVectors(rawText);

                    // dispatch the clean text over gRPC to the python inferance engine
                    // return the reactive flux stream of individual token as they are generated by the GPU
                    return grpcClient.streamInference(userId,cleanText);
                })
                .map(tokenString -> {
                    // Map each incoming gRPC string token into an outbound WebSocket text frame.
                    return session.textMessage(tokenString);
                });
        // bind the outbound flux to the session send method.
        // backpressure is respectrd. if the client connection is slow, the reactive stream will automatically thottle
        //the upstream grpce consumption.
        return session.send(outFlux);
    }
}
