// Define the syntax and standard Java package options to generate the classes.
syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.companion.grpc";

// Define the InferenceService interface to enforce
// polymorphism in the backend.
service InferenceService {

  // Define a server-streaming RPC method.
  // The Python server will yield multiple TokenChunks
  // asynchronously for a single prompt.
  rpc StreamTokens (InferenceRequest) returns (stream TokenChunk);
  rpc GenerateEmbedding (EmbeddingRequest) returns (EmbeddingResponse);
  // The BUMP Profiler Endpoint
  rpc GenerateUserProfile (UserProfileRequest) returns (UserProfileResponse);
}
message EmbeddingRequest {
  string text = 1;
}
message EmbeddingResponse {
  repeated float embedding = 1; // "repeated float" is Protobuf's way of defining an array of floats
}
// Define the exact data parameters required for the request.
// This ensures type safety and limits the attack surface for
// injection at the network layer.
message InferenceRequest {
  string user_id = 1;
  string sanitized_prompt = 2; // Text strictly pre-filtered by Java for prompt injection
  string vector_context = 3;   // The retrieved episodic memory payload
  string rlAction = 4; // action choosing by the q-learning java agent 
}

// Define the streaming response payload.
message TokenChunk {
  string token = 1;
  bool is_complete = 2;
}
message UserProfileRequest {
  string user_id = 1;
  string raw_interaction_history = 2; // The raw logs to compress
}

message UserProfileResponse {
  string compressed_profile = 1; // The LLM-generated BUMP digital twin
}

